parameters = [
    "?template", "?file", "?path", "?document", "?shell", "?page", "?view", "?include", "?dir",
    "?action", "?module", "?download", "?content", "?load", "?style", "?theme", "?lang", "?form",
    "?layout", "?type", "?cmd", "?exec", "?execute", "?run", "?process", "?step", "?image", "?img",
    "?pic", "?photo", "?icon", "?avatar", "?thumb", "?picture", "?downloadfile", "?arch", "?video",
    "?media", "?play", "?stream", "?movie", "?music", "?song", "?track", "?id", "?item", "?category",
    "?group", "?folder", "?dirpath", "?filepath", "?viewfile", "?showfile", "?loadfile", "?config",
    "?action", "?load_module", "?page_id", "?content_id", "?section", "?chapter", "?book", "?article",
    "?news", "?product", "?item_id", "?doc", "?resource", "?doc_id", "?file_id", "?file_name", "?name",
    "?plugin", "?layout", "?output", "?design", "?engine", "?plugin_name", "?module_name", "?component",
    "?com", "?section_id", "?chapter_id", "?section_name", "?search", "?report", "?app", "?system",
    "?admin", "?load_view", "?show", "?display", "?part", "?part_id", "?form_id", "?input", "?load_input",
    "?req", "?req_id", "?form", "?form_name", "?entry", "?edit", "?change", "?update", "?step", "?next",
    "?previous", "?info", "?details", "?info_id", "?id_doc", "?view_item", "?show_item", "?preview",
    "?thumb_id", "?edit_id", "?edit_item", "?action_id", "?op", "?option", "?option_id", "?layout_id",
    "?color", "?theme_id", "?template_id", "?stylesheet", "?lang_id", "?language", "?lang_code", "?set",
    "?config_id", "?admin_path", "?sys", "?sys_path", "?system_path", "?tool", "?task", "?proc", "?proc_id",
    "?execute_id", "?run_id", "?command", "?order", "?query", "?sql", "?query_id", "?search_term", "?filter",
    "?filter_id", "?criteria", "?command_id", "?criteria_id", "?sql_id", "?category_id", "?menu", "?menu_id",
    "?nav", "?nav_id", "?nav_item", "?item_id", "?download_id", "?upload", "?upload_id", "?file_upload",
    "?file_path", "?dir_id", "?file_load", "?file_show", "?media_id", "?stream_id", "?media_name", "?video_id",
    "?music_id", "?audio_id", "?play_id", "?movie_id", "?track_id", "?song_id", "?track", "?audio", "?video",
    "?category_name", "?group_id", "?group_name", "?user_id", "?profile", "?profile_id", "?profile_pic",
    "?avatar_id", "?user_name", "?account", "?account_id", "?customer", "?client_id", "?client", "?employee_id",
    "?staff_id", "?staff", "?person", "?member_id", "?project", "?project_id", "?project_name", "?product_id",
    "?order_id", "?transaction_id", "?purchase_id", "?invoice_id", "?contract_id", "?agreement_id",
    "?client_name", "?user_info", "?login", "?auth", "?auth_id", "?auth_code", "?password", "?key", "?token",
    "?session", "?session_id", "?cookie", "?cookie_id", "?user_token", "?api", "?api_key", "?apikey", "?access",
    "?access_token", "?oauth", "?oauth_token", "?session_token", "?session_key", "?config_key", "?secret",
    "?jwt", "?jwt_token", "?authentication", "?auth_token", "?dashboard",
    "template", "file", "path", "document", "shell", "page", "view", "include", "dir",
    "action", "module", "download", "content", "load", "style", "theme", "lang", "form",
    "layout", "type", "cmd", "exec", "execute", "run", "process", "step", "image", "img",
    "pic", "photo", "icon", "avatar", "thumb", "picture", "downloadfile", "arch", "video",
    "media", "play", "stream", "movie", "music", "song", "track", "id", "item", "category",
    "group", "folder", "dirpath", "filepath", "viewfile", "showfile", "loadfile", "config",
    "action", "load_module", "page_id", "content_id", "section", "chapter", "book", "article",
    "news", "product", "item_id", "doc", "resource", "doc_id", "file_id", "file_name", "name",
    "plugin", "layout", "output", "design", "engine", "plugin_name", "module_name", "component",
    "com", "section_id", "chapter_id", "section_name", "search", "report", "app", "system",
    "admin", "load_view", "show", "display", "part", "part_id", "form_id", "input", "load_input",
    "req", "req_id", "form", "form_name", "entry", "edit", "change", "update", "step", "next",
    "previous", "info", "details", "info_id", "id_doc", "view_item", "show_item", "preview",
    "thumb_id", "edit_id", "edit_item", "action_id", "op", "option", "option_id", "layout_id",
    "color", "theme_id", "template_id", "stylesheet", "lang_id", "language", "lang_code", "set",
    "config_id", "admin_path", "sys", "sys_path", "system_path", "tool", "task", "proc", "proc_id",
    "execute_id", "run_id", "command", "order", "query", "sql", "query_id", "search_term", "filter",
    "filter_id", "criteria", "command_id", "criteria_id", "sql_id", "category_id", "menu", "menu_id",
    "nav", "nav_id", "nav_item", "item_id", "download_id", "upload", "upload_id", "file_upload",
    "file_path", "dir_id", "file_load", "file_show", "media_id", "stream_id", "media_name", "video_id",
    "music_id", "audio_id", "play_id", "movie_id", "track_id", "song_id", "track", "audio", "video",
    "category_name", "group_id", "group_name", "user_id", "profile", "profile_id", "profile_pic",
    "avatar_id", "user_name", "account", "account_id", "customer", "client_id", "client", "employee_id",
    "staff_id", "staff", "person", "member_id", "project", "project_id", "project_name", "product_id",
    "order_id", "transaction_id", "purchase_id", "invoice_id", "contract_id", "agreement_id",
    "client_name", "user_info", "login", "auth", "auth_id", "auth_code", "password", "key", "token",
    "session", "session_id", "cookie", "cookie_id", "user_token", "api", "api_key", "apikey", "access",
    "access_token", "oauth", "oauth_token", "session_token", "session_key", "config_key", "secret",
    "jwt", "jwt_token", "authentication", "auth_token", "dashboard"
]
commands = [
    "../../../../../etc/passwd",
]