path = [
    "signup", "login", "logout", "database", "secret", "app", "sms", "ipv4", "search",
    "disclaimer", "guest", "book", "buynow", "live", "artists", "demo", "ip", "internet",
    "malware", "hide", "register", "account", "join", "enroll", "disconnect", "legal",
    "bot", "history", "help", "username", "login.php", "signup.php", "userinfo.php",
    "tags", "hits", "porn", "pornstar", "best", "forum", "tos", "privacy", "notice",
    "file", "menu", "##", "support", "contact", "email", "login.asp", "gay", "categories",
    "exit", "gifs", "gif", "db", "datastore", "confidential", "private", "hidden", "secure",
    "password", "application", "software", "program", "text", "message", "web", "online",
    "network", "cyberspace", "net", "information", "dataset", "records", "details",
    "statistics", "repository", "archive", "utility", "admin", "owner", "member", "home",
    "settings", "chat", "friends", "profile", "store", "security", "2fa", "notify", "api",
    "password", "test", "ssh", "uploader", "administrator", "marketing", "flag", "user",
    "player", "main", "badge", "feedback", "version", "ascii", "hacking", "pentester",
    "learn", "dashboard", "workplace", "free", "developer", "room", "rooms", "manage",
    "view", "share", "proxy", "inject", "sql", "osint", "locate", "location", "details",
    "avatar", "phone", "social", "token", "id", "user", "delete", "remove", "cat",
    "anonymous", "emoji", "join", "leave", "left", "shell", "spy", "signin", "market",
    "create", "video", "rec", "edit", "run", "blog", "group", "about", "tg", "add", "paste",
    "extensions", "docs", "teams", "discord", "telegram", "join", "faq", "Upgrades", "hoa",
    "rules", "themes", "item", "buy", "welcome", "en", "fr", "index", "inventory", "users",
    "#!", "accessories", "trades", "premium", "giftcards", "playlist", "feed", "feed//history",
    "subscriptions", "update", "download", "stars", "project", "packages", "products", "sitemap",
    "archives", "events", "event", "templates", "services", "icons", "resources", "info",
    "partners", "graphics", "research", "module", "modules", "index.php", "slogin.php",
    "login.php", "socialnetworks", "rss", "img", "default", "keygen", "article", "classroom",
    "gay", "client", "clientes", "clients", "cloud", "cloudflare-resolve-to", "club", "cms",
    "cn", "co", "community", "ads", "acceptatie", "access", "accounting", "agenda", "alpha",
    "sex", "ad", "adm", "admin", "webmail", "sql", "mysql", "autodiscover", "autoconfig",
    "mobile", "go", "start", "files", "terminal", "linux", "downloads", "win", "windows",
    "stat", "wiki", "images", "image", "calendar", "stage", "gateway", "unix", "nginx", "wss",
    "miss", "staging-chat", "release-chat-service", "h2", "paper", "russian", "gf", "y",
    "site2", "wd", "mls", "printer", "registrar", "ff", "dell", "va", "vl", "avalon",
    "bugtracker", "offline", "ppc", "ppp", "r25", "e2", "psql", "releasephp", "submit",
    "backup3", "tel", "dns0", "staging-chat-service", "postfixadmin", "ck", "s20", "sauron",
    "econ", "liste", "save", "perlbal-release", "lan", "graphics2", "dev-chat", "ana-dev",
    "shadow", "savvis-dev-commondata", "holiday", "reader", "exmail", "hosting1", "solr",
    "database2", "name", "ads1", "3img", "coregw1", "che", "mx7", "aries", "devwowza", "np",
    "n1", "zsb", "mod", "technology", "vod5", "host6", "parents", "imgup-lb", "portaltest",
    "jwgl", "setup", "reservation", "img8", "enquetes", "ns34", "classified", "mpa", "leads",
    "urchin", "nav", "ces", "mike", "casper", "99", "tula", "photos4", "microsoft", "thumb",
    "temp2", "sandd-dev-commondata", "sci", "fs2", "sac", "drweb", "elib", "mir", "asa", 
    "tool", "wh", "seguro", "parts", "tcs", "teknobyen-gw2", "bid", "transparencia", "cic",
    "vi", "rec", "gifts", "hyperion", "communication", "imap2", "tftp", "moe", "pollux",
    "tuanwei", "pop1", "mapa", "photos5", "praca", "kiwi", "scs", "cricket", "line", "condor",
    "w6", "wb", "0", "fz", "geobanner", "vr", "oas", "tts", "http", "gift", "meta", "splash",
    "media3", "tf", "homes", "grad", "uni", "mds", "5", "mobility", "cy", "anunturi", "ceres",
    "sx", "sj", "29", "altair", "tim", "singapore", "count", "msa", "rw", "dn", "fin", "sbe",
    "iis", "estadisticas", "stolav-gw4", "chaos", "vancouver", "eis", "database1", "neptun",
    "openfire", "find", "sip1", "std", "rpc", "leon", "outgoing", "gauss", "notify", "destiny",
    "emc", "remote2", "mv", "core2", "nf", "enroll", "grace", "checkrelay", "oldwebmail", 
    "deal", "k2", "seattle", "s18", "toolbar", "turing", "allegro", "s30", "requests", 
    "request", "ig", "ds", "skin", "snap", "cart", "guestbook", "careers", "product", 
    "testing", "date", "time", "timeline", "vscode", "code", "copyright", "copy"
]
