payload_admin = [
    "admin", "admin.php", "wp-admin", "admin/login.php", "login", 
    "login.php", "administrator", "user", "dashboard", "admin/index.php", 
    "moderator", "users", "wp-login.php", "dashboard/index.php", "user.php", 
    "login_db", "account.php", "account", "admin/account.php", "admin/admin", 
    "admin/admin.php", "adminarea", "admin_area/login.php", "admin/cpanel.php", 
    "admin/dashboard.php", "administrator/login.php", "admin_login.php", 
    "admin/moderator.php", "adminpanel.php", "admin/upload.php", "db/admin.php", 
    "robots.txt", "admin1.html", "admin2.php", "admin2.html", "admin/cp.php", 
    "admin/cp.html", "administrator/", "administrator/index.html", 
    "administrator/index.php", "administrator/login.html", "administrator/account.html", 
    "administrator/account.php", "administrator.asp", "login.asp", "owner", 
    "formslogin/", "autologin/", "support_login/", "meta_login/", 
    "manuallogin/", "simpleLogin/", "member/", "newsadmin/", "adminpro/", 
    "Lotus_Domino_Admin/", "bbadmin/", "vmailadmin/", "Indy_admin/", 
    "ccp14admin/", "irc-macadmin/", "banneradmin/", "sshadmin/", 
    "phpldapadmin/", "macadmin/", "administratoraccounts/", "admin4_account/", 
    "admin4_colon/", "radmind-1/", "Super-Admin/", "AdminTools/", 
    "quanly.asp", "quanly.php", "quantri.php", "quantri.asp", 
    "quantriweb.asp", "admin_index.asp", "admin_index.php", "password.asp", 
    "password.php", "dangnhap.asp", "dangnhap.php", "user.php", 
    "user.asp", "database_connect.php", "database_connect.asp", 
    "database_connect.html", "database_connect", "database_connect/", 
    "admin/home.php", "admin/controlpanel.html", "admin/controlpanel.php", 
    "sysadmin.php", "sysadmin.html", "phpmyadmin/", "myadmin/", 
    "sysadmin.asp", "sysadmin/", "ur-admin.asp", "ur-admin.php", 
    "ur-admin.html", "ur-admin/", "Server.php", "Server.html", 
    "Server.asp", "Server/", "LiveUser_Admin/", "sys-admin/", 
    "typo3/", "panel/", "cpanel/", "cPanel/", "UserLogin/", 
    "login-us/", "acct_login/", "admin_area/", "bigadmin/", 
    "macadmin/", "administratoraccounts/", "admin4_account/", 
    "admin4_colon/", "radmind-1/", "Super-Admin/", "myadmin", 
    "siteadmin", "phpadmin", "phplogin", "sitebackup/", 
    "sitebuilder/", "sitechecker/", "siteconfig.inc.php", 
    "siteconfig/", "sitecontent/", "sitecontrol/", "sitecore/", 
    "sitecore_files/", "sitecrm/", "sitedata/", "sitedb.php", 
    "sitedesign/", "sitedev/", "sitedown.asp", "sitedown.php", 
    "sitedown/", "siteedit/", "siteelements/", "sitefiles/", 
    "sitefinity/", "siteforum/", "siteframe/", "sitegen/", 
    "siteglobals/", "sitegraphics/", "siteimages/", "siteimg/", 
    "siteindex/", "siteinfo/", "sitelets/", "sitelogin/", 
    "sitelogins/", "sitelogs/", "sitemaker/", "sitemaketool/", 
    "siteman/", "sitemanage/", "sitemanager.xml", "sitemanager/", 
    "sitemanager2/", "sitemap.gz", "sitemap.html", "sitemap.php", 
    "sitemap.tar.gz", "sitemap.xml", "sitemap.xml.gz", "sitemap/", 
    "sitemap1.php", "sitemap_gen/", "sitemap_previous.php", 
    "sitemap_xml/", "sitemapdotnet/", "sitemapgen/", 
    "sitemapgenerator/", "sitemaphtml/", "sitemaps.php", 
    "sitemaps/", "sitemapx.php", "sitemedia/", "sitemgr/", 
    "sitenews/", "siteobjects/", "siteoffice/", "sitepages/", 
    "sitepics/", "siteprefs.php", "sitepreview/", "siterefer/", 
    "siteroot.php", "sites.ini", "sites.json", "sites.php", 
    "sites.xml", "sites/", "sites/all/libraries/fckeditor/", 
    "sites/all/modules/fckeditor/", "sitesearch/", "siteserver/", 
    "siteserver/publishing/viewcode.asp", 
    "siteserver/publishing/viewcode.php", "sitesetup.php", 
    "sitesnagger/", "sitespeed/", "sitestats.php", "sitestats/", 
    "sitetemplate/", "sitetest/", "sitewide/", "siteworks/", 
    "siti/", "sitio/", "sitios/",
    "dashboard/settings", "control", "adminConsole", "adminportal", "secure/login", "management", 
    "cms/admin", "system/login", "backend", "access", "backoffice", "loginform", "siteadmin", 
    "moderator/admin", "login_admin", "user_login", "account_admin", "adm/admin", "adm_cp", 
    "auth/login", "config", "config.php", "config.inc", "conf/config.php", "webadmin", 
    "manage", "system/admin", "db/config", "db/database.sql", "auth", "cpanel_login", 
    "database_admin", "panel_login", "superadmin", "webadmin/login", "adminhome", "sysadmin", 
    "root", "access/login", "accounts", "supervisor", "developer", "adminpage", "admincenter", 
    "root/login", "login_page", "phpmyadmin/config", "dashboard/login", "wp-config.php", 
    "setup", "setup.php", "install.php", "install", "index.php", "index.html", "admin/index.php", 
    "wp-config.php", "settings", "api/login", "api/auth", "dashboard/settings", "userauth", 
    "signin", "sign_in", "signon", "db_admin", "phpmyadmin/index.php", "phpmyadmin/config-db.php", 
    "phpmyadmin/config.inc.php", "database_manager", "adminarea.php", "adm_cp", "cp", "portal", 
    "auth/admin", "staff", "sys_admin", "usercp", "webcp", "database_manager", "dba/admin", 
    "admin1.php", "root/admin", "admin-login", "admin-login.php", "admin-console", "management.php", 
    "site/login", "service/admin", "phpmyadmin/phpinfo.php", "config/config.php", "admin/tools", 
    "sys_admin", "login_admin.php", "accountsettings", "private", "config/db.php", "accounting", 
    "admin_management", "member/admin", "private/admin", "config/security", "userlogin", "auth/admin", 
    "auth/settings", "system_admin", "private/settings", "database_access", "site/manage", "config.json", 
    "backend/config.php", "secure_admin", "php/admin", "webmaster", "adminpanel/login", "editor", 
    "controlpanel/login", "site_management", "usermanagement", "admin_main", "adminmod", "mod/admin", 
    "user", "dashboard_main", "main_admin", "panel_admin", "control.php", "sitepanel", "admincontrol", 
    "siteadmin.php", "systemsettings", "accountpanel", "dbmanager", "usercontrol", "adminDashboard", 
    "admpanel", "sysadmin/login", "accounts/admin", "home/login", "portaladmin", "staff_login", 
    "portal/login", "manage/admin", "securepanel", "website/login", "webadmin/login.php", "members", 
    "admin_area", "users/login", "adm/user", "adm/settings", "login_access", "auth/settings", 
    "staffarea", "staff/settings", "controlpanel/admin", "service.php", "config/server.php", 
    "webmanager", "security/login", "adminSection", "adm/panel", "adminzone", "accountlogin", 
    "panel/login", "auth/login.php", "website/admin", "system/config", "access/admin", "controlcenter", 
    "dbconfig", "main.php", "controlpanel", "adminhome.php", "loginportal", "controlarea", "settings.php", 
    "super_user", "server/login", "staff_login.php", "adminpage.php", "console", "usr/login", 
    "cp/index.php", "sys/admin", "adminhome", "admin-center", "access_control", "signin/login", 
    "security/admin", "services/admin", "cp/config.php", "database/admin", "console.php", "app/admin", 
    "content/login", "dbadmin.php", "sitepanel.php", "user_account", "dashboard.php", "sysadmin_panel", 
    "admin_login", "console/login", "webpanel", "appsettings", "backend/admin", "webmaster.php", 
    "dashboard/user", "adminconsole", "admintool", "datamanager", "webmanager", "panel/admin", 
    "manage/admin.php", "auth/settings", "backendpanel", "admin-console", "userpanel", "admin/user_login", 
    "admin_console", "admin_login.php", "user_center", "phpmyadmin/index.html", "admin/config.php", 
    "home.php", "main_admin", "dashboard/config", "admin/config", "config_file.php", "main_admin/login", 
    "db/setup.php", "systemsettings.php", "admin_panel", "console/dashboard", "users/admin", 
    "controlpanel.php", "admin_login_page", "management/login", "db_manager", "dashboard/admin", 
    "manage/users", "login_console", "adminarea/login.php", "backendadmin", "auth/admin/login",
    "admincp", "admin1", "adminfiles", "dashboard/config", "db/config.inc", "webcpanel", "adminconfig", 
    "userpanel", "account_admin", "manageusers", "login/admin", "admin_area", "config/settings", 
    "admincontrol", "admininterface", "manager/login", "managerpanel", "cms/config", "core/admin", 
    "admintools", "authpanel", "configurations", "webadmin.php", "admintools.php", "userconfig", 
    "data/login", "secure/admin", "adminpages", "securitypanel", "support/admin", "adminsys", 
    "service/config", "servlet/admin", "accessadmin", "member/login", "usercontrolpanel", 
    "secure_dashboard", "admingateway", "settingspanel", "configtool", "configcenter", "manager.php", 
    "configuration", "admininterface.php", "server/admin", "backend/login", "portalconfig", 
    "usermanager", "secure/config", "adminaccount", "admtools", "webtools", "webconfig", "adminsection", 
    "admintool.php", "cmsadmin", "systemcontrol", "serverpanel", "adminsettings", "webcontrol", 
    "appadmin", "cms/login", "web_admin", "admin_module", "dashboard/settings", "admin_console", 
    "config/index.php", "user/portal", "controladmin", "controlsettings", "panel/config", "securearea", 
    "members/login", "admin_tools", "tools/login", "management_panel", "loginhandler", "adm", 
    "admpanel", "admin_handler", "securityconsole", "secure_login", "admin_portal", "managerarea", 
    "managerconsole", "webadmincontrol", "administration", "systemconfig", "configpanel", "admconfig", 
    "adminview", "rootcontrol", "loginform.php", "logincms", "user_admin", "accesspanel", 
    "accountmanagement", "admin_tool", "webtools/admin", "secure/admin_login", "cms/config.php", 
    "panelaccess", "controlcenter/login", "panel_login", "admincpanel", "admin_tools.php", "usr_login", 
    "admin_manager", "accountcontrol", "syscontrol", "config_admin", "panel_tools", "dashboard/admin.php", 
    "system_control", "access_admin", "config_manager", "dbcontrol", "adminweb", "databaseadmin", 
    "webadmin/config", "configdashboard", "portalaccess", "user_dashboard", "administratorpanel", 
    "manager_settings", "adminarea/config", "web_control", "login_dashboard", "sysadmin_tools", 
    "syscontrolpanel", "backendconfig", "authdashboard", "managercontrol", "configtool.php", 
    "admin/settings", "admin_home", "configtools", "manageradmin", "systemadmin", "adminportal/config", 
    "login_user", "admin_dashboard", "authportal", "system_manager", "systemadmin/config", 
    "manager_login", "managementtools", "usercontrolpanel", "config_secure", "db_manager", 
    "adminmodule", "configadmin", "admintool_config", "cms/settings", "panel_home", "control_config", 
    "admininterface/login", "configpanel", "secure_admin", "sysmanager", "managementconsole", 
    "admincenter/login", "webconfig/login", "managerdashboard", "securepanel", "userdashboard", 
    "adminboard", "core/config", "admin_auth", "admindashboard", "admincpanel/config", "admin_web", 
    "adminconsole/login", "securetools", "systemadmin/tools", "systempanel", "adminaccess", 
    "admcontrol", "sysadmin/dashboard", "portaladmin/login", "config_area", "dashboard_access", 
    "admindashboard/config", "sysconfig", "manager_dashboard", "admin/management", "dashboardconsole", 
    "sysadminconfig", "panel/settings", "usermanagement", "securelogin", "adminsyslogin", 
    "secureaccount", "admincontrolpanel", "configuration/admin", "loginsecure", "adminsettings/config", 
    "adminconsolepanel", "account_admin_panel", "managepanel", "adminsite", "cmsadminpanel", 
    "account_access", "systemaccess", "authpanel/login", "admindashboard/login", "controlaccess", 
    "configweb", "admincenter", "admin/configtools", "configweb/admin", "dashboard_tools", 
    "accountmanagementpanel", "login_management", "controlinterface", "dashboardcontrol", 
    "system_manager_login", "configsecure", "admin/console", "cms_login", "usercontrolpanel", 
    "system_dashboard", "control_manager", "adminmanager", "controltools", "secure_adminpanel", 
    "siteadminlogin", "db/config", "managerconsole", "dashboard_manager", "sysadmincontrol", 
    "auth/admin", "manage_console", "adminsecurity", "web_admin_console", "adminservice", 
    "securityadmin", "admin_tools", "adm_manager", "usercontrolpanel", "admin/security", 
    "cms_manager", "management_portal", "cms_admin_login", "configlogin", "securemanagement", 
    "portal_admin", "adminservices", "user_security", "db/adminpanel", "adminsystemtools", 
    "adminsettings", "configpanel_login", "admintoolscontrol", "controlboard", "adminportaltools", 
    "panel_secure", "dashboardsettings", "authcontrol", "siteadminpanel", "userinterface", 
    "systemadmininterface", "securetools", "db_login", "loginconfig", "adminsystem", "admcontrolpanel",
    "wp-content/uploads/2018/03/mini.php",
    "wp-content/uploads/2018/03/c99.php",
    "wp-content/uploads/2018/03/b37k.php",
    "wp-content/uploads/2018/03/ok.php",
    "wp-content/uploads/2018/03/upup.php",
    "wp-content/uploads/2018/03/vuln.php",
    "wp-content/uploads/2018/03/succes.php",
    "wp-content/uploads/2018/03/acces.php",
    "wp-content/uploads/2018/03/sukses.php",
    "wp-content/uploads/2018/03/akses.php",
    "wp-content/uploads/2018/03/backdoor.php",
    "wp-content/uploads/2018/03/jembut.php",
    "wp-content/uploads/2018/03/r00t.php",
    "wp-content/uploads/2018/03/indrajith.php",
    "wp-content/uploads/2018/03/Indrajith.php",
    "wp-content/uploads/2018/03/Indrajith_v1.php",
    "wp-content/uploads/2018/03/Indrajith_v2.php",
    "wp-content/uploads/2018/03/bol.php",
    "wp-content/uploads/2018/03/shellku.php",
    "wp-content/uploads/2018/04/shell.php",
    "wp-content/uploads/2018/04/Shell.php",
    "wp-content/uploads/2018/04/cok.php",
    "wp-content/uploads/2018/04/up.php",
    "upload.php",
    "wp-content/uploads/2018/04/mini.php",
    "wp-content/uploads/2018/04/backdor.php",
    "wp-content/uploads/2018/04/myshell.php",
    "wp-content/uploads/2018/04/c99.php",
    "wp-content/uploads/2018/04/dark.php",
    "wp-content/uploads/2018/04/root.php",
    "wp-content/uploads/2018/04/jembut.php",
    "wp-content/uploads/2018/04/kontol.php",
    "wp-content/uploads/2018/04/ok.php",
    "wp-content/uploads/2018/04/upup.php",
    "wp-content/uploads/2018/04/IndoXploit.php",
    "wp-content/uploads/2018/04/indoxploit.php",
    "wp-content/uploads/2018/04/IndoXploit_v1.php",
    "wp-content/uploads/2018/04/IndoXploit_v2.php",
    "wp-content/uploads/2018/04/IndoXploit_v3.php",
    "wp-content/uploads/2018/04/b37k.php",
    "wp-content/uploads/2018/05/shell.php",
    "wp-content/uploads/2018/06/shell.php",
    "wp-content/uploads/2018/07/namashellLu.php",
    "wp-content/uploads/2018/08/shell.php",
    "wp-content/uploads/2018/09/shell.php",
    "wp-content/uploads/2018/10/shell.php",
    "wp-content/uploads/2018/11/shell.php",
    "wp-content/uploads/2018/12/shell.php",
    "wp-content/plugins/wp-symposium/server/php/Shell.php",
    "wp-content/plugins/wp-symposium/server/php/Sh3ll.php",
    "wp-content/plugins/wp-symposium/server/php/b37k.php",
    "wp-content/plugins/wp-symposium/server/php/up.php",
    "wp-content/plugins/wp-symposium/server/php/c99.php",
    "wp-content/plugins/wp-symposium/server/php/wp.php",
    "wp-content/plugins/wp-symposium/server/php/sym.php",
    "wp-content/plugins/wp-symposium/server/php/upload.php",
    "wp-content/plugins/wp-symposium/server/php/succes.php",
    "wp-content/plugins/wp-symposium/server/php/php.php",
    "wp-content/plugins/wp-symposium/server/php/IndoXploit.php",
    "wp-content/plugins/wp-symposium/server/php/Indrajith.php",
    "wp-content/plugins/wp-symposium/server/php/indrajith.php",
    "wp-content/plugins/wp-symposium/server/php/berhasil.php",
    "wp-content/plugins/wp-symposium/server/php/yup.php",
    "wp-content/plugins/wp-symposium/server/php/myshell.php",
    "wp-content/plugins/wp-symposium/server/php/shell.php",
    "wp-content/plugins/wp-symposium/server/php/symposium.php",
    "wp-content/plugins/wp-symposium/server/php/_func.php",
    "wp-content/plugins/wp-symposium/server/php/shellgua.php",
    "wp-content/plugins/wp-symposium/server/php/shellgue.php",
    "wp-content/plugins/wp-symposium/server/php/server.php",
    "wp-content/plugins/wp-symposium/server/php/admin.php",
    "wp-content/plugins/wp-symposium/server/php/oke.php",
    "wp-content/plugins/wp-symposium/server/php/ok.php",
    "wp-content/plugins/wp-symposium/server/php/mini.php",
    "wp-content/plugins/wp-symposium/server/php/Mini.php",
    "wp-content/plugins/wp-symposium/server/php/min.php",
    "wp-content/plugins/wp-symposium/server/php/1n73ction.php",
    "wp.zip",
    "wp-content/plugins/disqus-comment-system/WSO.php",
    "images/root.php",
    "wp-content/plugins/disqus-comment-system/Sym.php",
    "wp-content/plugins/disqus-comment-system/c22.php",
    "wp-content/plugins/disqus-comment-system/c100.php"
]
